Module HelpMod
    Sub ShowHelp()
        xtrace("Print Help")

        Console.WriteLine(" ")
        Console.WriteLine("---- " & AppName & " V" & AppVer & " ------------------------------------------------")
        Console.WriteLine(" Switches:")
        Console.WriteLine("  -b = Prints a bullet before the wait line")
        Console.WriteLine("  -h = Show this help page")
        Console.WriteLine("  /? = Show this help page")
        Console.WriteLine("  -p = Pause, asks for a key strike")
        Console.WriteLine("  -v = Verbose")
        Console.WriteLine(" ")
        Console.WriteLine("  --help    = The same as -h")
        Console.WriteLine("  --w=<int> = Set the wait time in seconds, the default is " & SwWait.ToString)
        Console.WriteLine("  --xhelp = extended help")
        Console.WriteLine(" ")
        Console.WriteLine(" Arguments:")
        Console.WriteLine(" ")
        Console.WriteLine(" Environment:")
        Console.WriteLine("  TA_BATCH=TRUE prevents user entry and sets a standard delay")
        Console.WriteLine(" ")
        Console.WriteLine(" Examples: ")
        Console.WriteLine("  wait             Wait the default delay (" & SwWait.ToString & " Sec)")
        Console.WriteLine("  wait --w=2       Wait 2 seconds")
        Console.WriteLine("  wait -p          The same as pause")
        Console.WriteLine("  wait 2           The same as wait --w=2 (for backward compatibility)")
        Console.WriteLine(" ")
        Console.WriteLine(" ")
        Console.WriteLine(" Log file = " & LogFile)
        Console.WriteLine(" Hans.van.Buitenen@philips.com")
        Console.WriteLine(" ")
        Console.WriteLine("----------------------------------------------------------------")
        Console.WriteLine(" ")

        wait(2)
    End Sub

    Sub ShowXHelp()
        xtrace("Print Help")

        Console.WriteLine(" ")
        Console.WriteLine("---- " & AppName & " V" & AppVer & " XHelp ------------------------------------------------")
        Console.WriteLine(" Switches:")
        Console.WriteLine("  -b = Prints a bullet before the wait line")
        Console.WriteLine("  -h = Show this help page")
        Console.WriteLine("  /? = Show this help page")
        Console.WriteLine("  -p = Pause, asks for a key strike")
        Console.WriteLine("  -v = Verbose")
        Console.WriteLine(" ")
        Console.WriteLine("  --help  = The same as -h")
        Console.WriteLine("  --w=<int> = Set the wait time in seconds, the default is " & SwWait.ToString)
        Console.WriteLine("  --xhelp = extended help")
        Console.WriteLine(" ")
        Console.WriteLine(" Arguments:")
        Console.WriteLine(" ")
        Console.WriteLine(" Log file = " & LogFile)
        Console.WriteLine(" ")
        Console.WriteLine(" Examples: ")
        Console.WriteLine("  Command          |Result                      |Remark")
        Console.WriteLine(" ------------------+----------------------------+---------")
        Console.WriteLine("  wait -p          |Type any key to continiue...|Pause")
        Console.WriteLine("  wait             | * Wait 6 Sec...            |Default delay")
        Console.WriteLine("  wait --w=4       |Wait 4 Sec...               |")
        Console.WriteLine("  wait /t 4        |Wait 4 Sec...               |Backward compatibility")
        Console.WriteLine("  wait 4           |Wait 4 Sec...               |Backward compatibility")
        Console.WriteLine("  wait -b          | * Wait 6 Sec...            |Default delay + Bullet")
        Console.WriteLine("  wait -b --w=4    | * wait 4 Sec...            |")
        Console.WriteLine("  wait -pb         | * Type any key to continiue...")
        Console.WriteLine(" ")
        Console.WriteLine(" Log file = " & LogFile)
        Console.WriteLine(" Hans.van.Buitenen@philips.com")
        Console.WriteLine(" ")
        Console.WriteLine("----------------------------------------------------------------------")
        Console.WriteLine(" ")

        wait(2)
    End Sub
End Module
